import { Montserrat } from "next/font/google";
import { Average_Sans } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import MouseFollower from "@/components/MouseFollower";



const roboto = Montserrat({
  variable:"--font-roboto",
  subsets: ["latin"],
  weight:['300','400','500','600','700','800']
});

const Avg_sans = Average_Sans({
  variable:"--font-average",
  subsets: ["latin"],
  weight:['400',]
});


export const metadata = {
  title: "Xtreme Verge",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${roboto.variable} ${Avg_sans.variable} antialiased`}
      >
        <MouseFollower />
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
